services:
  - type: web
    name: PortfolioApp
    runtime: docker
    buildCommand: docker build -t portfolioapp .
    startCommand: docker run -e PORT=$PORT -p 10000:10000 portfolioapp
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
