services:
  - type: web
    name: PortfolioApp
    runtime: docker
    buildCommand: docker build -t portfolioapp .
    startCommand: dotnet ProjectPortfolio.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
